name: Post Discord Image Card

on:
  workflow_dispatch:

jobs:
  send:
    runs-on: ubuntu-latest
    steps:
      - name: Send image card
        run: |
          curl -X POST -H "Content-Type: application/json" \
          -d '{
            "embeds": [{
              "color": 16758465,
              "image": { "url": "https://raw.githubusercontent.com/ella-bektas/wis-discord/main/welcome-divas.png" }
            }]
          }' \
          ${{ secrets.DISCORD_WELCOME_WEBHOOK }}
